### ISSUE TITLE
Allow setting custom TextureImporterPlatformSettings

### ISSUE THREAD

**Issue by rafaelGuerreiro** [Elringus/SpriteDicing#24]
After dicing and generating the diced texture, it'd be nice to automatically apply custom compression settings.

This would make rebuilding it a lot easier because every time it resets to default.

I saw there is a class called `UnityEditor.TextureImporterPlatformSettings` that seems to hold this information, but I'm not experienced enough in UnityEditor to know how to include it in the `SpriteDicing.Editors.DicedSpriteAtlasEditor` class.

<img width="575" alt="Screen Shot 2022-04-08 at 12 54 36 PM" src="https://user-images.githubusercontent.com/836370/162517247-dcb3e101-81b7-42d1-b639-a57a3cd748d3.png">
.

**Comment by Elringus** [comment]
Thanks for the suggestion, that's indeed something worth solving. I've drafted a solution in #25; please let me know if it'll work.
