### ISSUE TITLE
Publish semver tag for OpenUPM

### ISSUE THREAD

**Issue by laicasaane** [elringus/SpriteDicing#38]
For the ease of installing your package via OpenUPM, please publish with semver tags (e.g. `1.10.0`) instead of `v1.10`. The tag string should match the version string defined in your `package.json`.
Many thanks!

From OpenUPM:
https://openupm.com/packages/com.elringus.spritedicing/

> **No valid git tag**
> OpenUPM only tracks Git tags that adhere to the semver convention. If a valid Git tag is not found, the package will not appear on the package listing.

**Comment by elringus** [comment]
Thanks, I've updated the tag.
