### ISSUE TITLE
Sprite Centers are wrong

### ISSUE THREAD

**Issue by zsculpt** [Elringus/SpriteDicing#8]
I'm still having this problem with the latest 1.1 package. The first image is my actual PNG with alpha. As you can see, the sprite is near the bottom half of the PNG. The second image is with the pivot point set to default (the sprite has been re-centered), and the third image is with the pivot point with the checkbox "Keep Original" (the sprite has been offset based on the lower left-hand corner). How do I make this use the actual position of the sprite on the PNG?

![Diced Sprites Problem](https://user-images.githubusercontent.com/5686852/100526932-e6a8c480-318a-11eb-8e84-f1ea4227834c.jpg)

**Comment by Elringus** [comment]
Check the animation scene in the repro, keep original works fine there.

**Comment by zsculpt** [comment]
I've looked at that example and it has the same problem. "Keep Original" sets the pivot point to the lower left-left hand corner, which is not correct. The center should be the center of the source PNG.

**Comment by zsculpt** [comment]
Here you can see what's happening. Left image is the sprite dicing animation and the right image is a Unity sprite from the same PNG:

![Sprite-Dicing-Error-2](https://user-images.githubusercontent.com/5686852/100636894-723b6600-32ef-11eb-9506-d2c85b732ccb.jpg)

**Comment by Elringus** [comment]
That's by design. `Keep Original` preserves relative position of the pivot to the source texture content. The textures you've mentioned have transparent "slack", that's why it looks like the pivot has offset from the actual content.

**Comment by zsculpt** [comment]
Is it possibly for you to add in a mode that would preserve the position based on the dimensions of the texture? My use case is an app with literally hundreds of icons that are all a fixed size (256x256). The problem is when I use the SpriteDicing tools over Unity’s built-in sprites, their positions all get completely out of whack in their alignments to the UI. Please consider adding support for this, as I feel it is a quite common setup with UI.

**Comment by Elringus** [comment]
Keep pivot does just that. It preserves position of the pivot relative to the source texture. The pivot will always be at the bottom-left corner, though (0, 0). I guess it's possible to add an option to control the original pivot position as well, but that's not something I personally need atm; PRs are welcome, though.

**Comment by zsculpt** [comment]
Right, and that’s what I’m getting at. Most UI stuff (when it comes to icons on buttons and such) uses a default pivot point that is at the center of the icon. There are literally hundreds of icons in this app with more being added every time I update it. Just please take it under consideration if it’s a feature that could be easily implemented for you, it would be hugely appreciated.

Cheers,

**Comment by Elringus** [comment]
If you want centered pivot, just disable keep and and set it at 0.5,0.5

**Comment by Elringus** [comment]
> 
> 
> Keep pivot does just that. It preserves position of the pivot relative to the source texture. The pivot will always be at the bottom-left corner, though (0, 0). I guess it's possible to add an option to control the original pivot position as well, but that's not something I personally need atm; PRs are welcome, though.

I've added the option in new release. When `Keep Pivot` is enabled and source texture has an associated sprite (set via [sprite editor](https://docs.unity3d.com/Manual/SpriteEditor.html)), pivot of the sprite will be preserved (relative to the dimensions of the source texture).
